apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vdul6lg30-java-springboot
  janus-idp.io/tekton: vdul6lg30-java-springboot
  backstage.io/kubernetes-id: vdul6lg30-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vdul6lg30-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
